# Generated by Django 4.1.5 on 2023-01-30 15:24

from django.db import migrations


def create_topic(apps, schema_editor):
    FCMTopic = apps.get_model("firebase_push", "FCMTopic")
    FCMTopic.objects.create(name="default", description="Default topic")


class Migration(migrations.Migration):
    dependencies = [
        ("firebase_push", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_topic)]
